title: Hipacc
repository: hipacc/hipacc
description: The Heterogeneous Image Processing Acceleration Framework
google_analytics:
show_downloads: false
theme: jekyll-theme-slate

plugins:
  - jekyll-mentions
  - jekyll-github-metadata
